# Generated by Django 2.0.10 on 2019-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0008_auto_20190213_0253'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managing',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.City'),
        ),
    ]
