# Generated by Django 2.0.10 on 2019-02-12 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('creator', models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('comstate', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('modem_number', models.CharField(max_length=120)),
                ('latitude', models.CharField(max_length=120)),
                ('longitude', models.CharField(max_length=120)),
                ('pump_count', models.CharField(max_length=120)),
                ('pressure', models.BooleanField(default=False)),
                ('pump_1_freq', models.CharField(max_length=120)),
                ('pump_1_current', models.CharField(max_length=120)),
                ('pump_2_freq', models.CharField(max_length=120)),
                ('pump_2_current', models.CharField(max_length=120)),
                ('pump_3_freq', models.CharField(max_length=120)),
                ('pump_3_current', models.CharField(max_length=120)),
                ('city', models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.City')),
                ('creator', models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('creator', models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('creator', models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pump',
            name='sector',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.Sector'),
        ),
        migrations.AddField(
            model_name='pump',
            name='town',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.Town'),
        ),
    ]
