# Generated by Django 2.0.10 on 2019-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='city',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.City'),
        ),
        migrations.AddField(
            model_name='sector',
            name='town',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.Town'),
        ),
        migrations.AddField(
            model_name='town',
            name='city',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.City'),
        ),
    ]
