# Generated by Django 2.0.10 on 2019-02-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0002_auto_20190212_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='city',
        ),
    ]
