# Generated by Django 2.0.10 on 2019-02-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0003_remove_sector_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='town',
        ),
    ]
