# Generated by Django 2.0.10 on 2019-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0004_auto_20190212_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='pump_2_current',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_2_freq',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_3_current',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_3_freq',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
