# Generated by Django 2.0.10 on 2019-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0005_auto_20190213_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='city',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.City'),
        ),
        migrations.AddField(
            model_name='pump',
            name='town',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.Town'),
        ),
        migrations.AddField(
            model_name='sector',
            name='city',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='pumps.City'),
        ),
    ]
