# Generated by Django 2.0.10 on 2019-02-12 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pumps', '0006_auto_20190213_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='town',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='manager',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='creator',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pump',
            name='sector',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='pump_set', to='pumps.Sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='town',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='sector_set', to='pumps.Town'),
        ),
        migrations.AlterField(
            model_name='town',
            name='city',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='town_set', to='pumps.City'),
        ),
    ]
