# Generated by Django 2.0.10 on 2019-02-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0007_auto_20190213_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='city',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='town',
            name='creator',
        ),
    ]
