# Generated by Django 2.0.10 on 2019-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0008_auto_20190213_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='latitude',
            new_name='operating_rate',
        ),
        migrations.RenameField(
            model_name='pump',
            old_name='longitude',
            new_name='power',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='comstate',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='modem_number',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_1_current',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_1_freq',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_2_current',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_2_freq',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_3_current',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_3_freq',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_count',
        ),
        migrations.AddField(
            model_name='pump',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pump',
            name='current',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pump',
            name='freq',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='dis_pressure',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='lat',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='lon',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='low_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='modem_number',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_1_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_2_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_3_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_4_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_count',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pump_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='set_pressure',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sector',
            name='water_level',
            field=models.BooleanField(default=False),
        ),
    ]
