# Generated by Django 2.0.10 on 2019-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0009_auto_20190601_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='discharge',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='pressure',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
