# Generated by Django 2.0.10 on 2019-05-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0010_auto_20190601_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='pressure',
        ),
    ]
